# charts/kafka-connect/templates/debezium-connector.yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: postgres-debezium-connector
  namespace: {{ .Values.global.namespace }}
  labels:
    strimzi.io/cluster: {{ .Values.kafkaConnect.clusterName }}
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: {{ .Values.debezium.tasksMax }}
  config:
    database.hostname: {{ .Values.postgresql.host }}
    database.port: "{{ .Values.postgresql.port }}"
    database.user: 
      valueFrom:
        secretKeyRef:
          name: postgres-credentials
          key: username
    database.password:
      valueFrom:
        secretKeyRef:
          name: postgres-credentials
          key: password
    database.dbname: {{ .Values.postgresql.database }}
    database.server.name: {{ .Values.debezium.serverName }}
    slot.name: {{ .Values.debezium.slotName }}
    plugin.name: pgoutput
    publication.autocreate.mode: filtered
    table.include.list: {{ .Values.debezium.tableIncludeList }}
    topic.prefix: {{ .Values.debezium.topicPrefix }}
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false
