apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka-connect.fullname" . }}
  labels:
    {{- include "kafka-connect.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kafka-connect.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kafka-connect.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      {{- toYaml .Values.initContainers | nindent 6 }}
      containers:
      - name: kafka-connect
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: rest-api
          containerPort: 8083
          protocol: TCP
        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
          value: "1"
        - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR  
          value: "1"
        - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
          value: "1"
        volumeMounts:
        - name: plugins
          mountPath: /usr/share/confluent-hub-components
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: plugins
        emptyDir: {}
