apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect
  namespace: {{ .Values.global.namespace | default "data-platform-dev" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      containers:
        - name: kafka-connect
          image: confluentinc/cp-kafka-connect:7.4.0
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.s3.secretName }}
                  key: {{ .Values.global.s3.accessKeyKey }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.s3.secretName }}
                  key: {{ .Values.global.s3.secretKeyKey }}
          ports:
            - containerPort: 8083 