# charts/kafka-connect/templates/s3-sink-connector.yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: s3-sink-connector
  namespace: {{ .Values.global.namespace }}
  labels:
    strimzi.io/cluster: {{ .Values.kafkaConnect.clusterName }}
spec:
  class: io.confluent.connect.s3.S3SinkConnector
  tasksMax: {{ .Values.s3Sink.tasksMax }}
  config:
    topics.regex: "{{ .Values.debezium.topicPrefix }}.*"
    s3.bucket.name: {{ .Values.aws.s3.bucket }}
    s3.region: {{ .Values.aws.s3.region }}
    aws.access.key.id:
      valueFrom:
        secretKeyRef:
          name: aws-credentials
          key: access-key-id
    aws.secret.access.key:
      valueFrom:
        secretKeyRef:
          name: aws-credentials
          key: secret-access-key
    format.class: io.confluent.connect.s3.format.parquet.ParquetFormat
    flush.size: {{ .Values.s3Sink.flushSize }}
    rotate.interval.ms: {{ .Values.s3Sink.rotateIntervalMs }}
    partitioner.class: io.confluent.connect.storage.partitioner.TimeBasedPartitioner
    path.format: "'year'=YYYY/'month'=MM/'day'=dd/'hour'=HH"
    timestamp.extractor: Record
    locale: US
    timezone: UTC
    storage.class: io.confluent.connect.s3.storage.S3Storage
