apiVersion: v2
name: data-platform
description: A data platform for CDC, streaming, and analytics with environment-specific namespaces and external secrets.
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: redpanda
    version: ">=0.1.0"
    repository: "file://charts/redpanda"
  - name: debezium
    version: ">=0.1.0"
    repository: "file://charts/debezium"
  - name: kafka-connect
    version: ">=0.1.0"
    repository: "file://charts/kafka-connect"
  - name: flink
    version: ">=0.1.0"
    repository: "file://charts/flink"
  - name: monitoring
    version: ">=0.1.0"
    repository: "file://charts/monitoring" 