# Local development overrides
redpanda:
  storage:
    persistentVolume:
      size: 10Gi
  resources:
    cpu:
      cores: 0.5
    memory:
      container:
        max: 1Gi

minio:
  persistence:
    size: 20Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 250m

flink:
  jobmanager:
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m
  
  taskmanager:
    resources:
      requests:
        memory: 1Gi
        cpu: 250m
      limits:
        memory: 2Gi
        cpu: 500m
