apiVersion: v1
kind: Service
metadata:
  name: debezium
  namespace: {{ .Values.global.namespace | default "data-platform-dev" }}
spec:
  type: ClusterIP
  selector:
    app: debezium
  ports:
    - port: 8083
      targetPort: 8083 