# Flink configuration - no hardcoded values
image:
  repository: {{ .Values.global.flink.image.repository | default "flink" }}
  tag: {{ .Values.global.flink.image.tag | default "1.18.0" }}
  pullPolicy: {{ .Values.global.images.pullPolicy }}

jobmanager:
  replicaCount: {{ .Values.global.flink.jobmanager.replicas | default 1 }}
  
  service:
    type: {{ .Values.global.flink.jobmanager.service.type | default "ClusterIP" }}
    port: {{ .Values.global.flink.jobmanager.service.port | default 8081 }}
    
  resources: {{ .Values.global.flink.jobmanager.resources | default .Values.global.resources.medium | toYaml | nindent 4 }}

taskmanager:
  replicaCount: {{ .Values.global.flink.taskmanager.replicas | default 2 }}
  
  resources: {{ .Values.global.flink.taskmanager.resources | default .Values.global.resources.large | toYaml | nindent 4 }}

# Flink configuration
config:
  flink:
    jobmanager.rpc.address: {{ .Values.global.flink.config.jobmanagerRpcAddress | default "flink-jobmanager" | quote }}
    taskmanager.numberOfTaskSlots: {{ .Values.global.flink.config.taskSlots | default 2 | quote }}
    parallelism.default: {{ .Values.global.flink.config.parallelism | default 2 | quote }}
    
    # Checkpointing configuration
    state.backend: {{ .Values.global.flink.config.stateBackend | default "filesystem" | quote }}
    state.checkpoints.dir: {{ printf "s3://%s/checkpoints" .Values.global.s3.bucket | quote }}
    state.savepoints.dir: {{ printf "s3://%s/savepoints" .Values.global.s3.bucket | quote }}
    
    # S3 filesystem configuration
    s3.access-key: "{{ .Values.global.aws.accessKey }}"
    s3.secret-key: "{{ .Values.global.aws.secretKey }}"
    s3.endpoint: {{ .Values.global.s3.endpoint | default "https://s3.amazonaws.com" | quote }}
    s3.endpoint.region: {{ .Values.global.aws.region | quote }}
    s3.path.style.access: {{ .Values.global.s3.pathStyleAccess | default false | quote }}
    
    # Checkpointing intervals
    execution.checkpointing.interval: {{ .Values.global.flink.config.checkpointInterval | default 30000 | quote }}
    execution.checkpointing.min-pause: {{ .Values.global.flink.config.checkpointMinPause | default 500 | quote }}
    
    # Restart strategy
    restart-strategy: {{ .Values.global.flink.config.restartStrategy | default "fixed-delay" | quote }}
    restart-strategy.fixed-delay.attempts: {{ .Values.global.flink.config.restartAttempts | default 3 | quote }}
    restart-strategy.fixed-delay.delay: {{ .Values.global.flink.config.restartDelay | default "10s" | quote }}

# Job configuration
job:
  enabled: {{ .Values.global.flink.job.enabled | default true }}
  jarPath: {{ .Values.global.flink.job.jarPath | default "/opt/flink/lib/cdc-job.jar" | quote }}
  className: {{ .Values.global.flink.job.className | default "CDCProcessor" | quote }}
  args: {{ .Values.global.flink.job.args | default list | toYaml | nindent 4 }}
  
# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 9999
  fsGroup: 9999
