# environments/values-staging.yaml
global:
  environment: staging
  
redpanda:
  replicas: 3
  resources:
    limits:
      memory: 2Gi
      cpu: 1000m
    requests:
      memory: 1Gi
      cpu: 500m
  
kafkaConnect:
  replicas: 2
  resources:
    limits:
      memory: 1Gi
      cpu: 500m
  
flink:
  jobManager:
    resources:
      memory: 1Gi
      cpu: 500m
  taskManager:
    replicas: 3
    resources:
      memory: 2Gi
      cpu: 1000m
      
aws:
  s3:
    bucket: "{{ .Values.global.environment }}-td-pipeline-data"
    region: "us-east-1"
    
postgresql:
  external: true
  host: "host.docker.internal"  # For local Postgres
  port: 5432
  database: "td_pipeline"
