{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.service.type "ExternalName" }}
  type: ExternalName
  externalName: {{ .Values.service.externalName }}
  {{- else }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
    name: postgresql
{{- end }}
