apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
        - name: redpanda
          image: vectorized/redpanda:latest
          ports:
            - containerPort: 9092
