apiVersion: v1
kind: Service
metadata:
  name: redpanda
  namespace: {{ .Values.global.namespace | default "data-platform-dev" }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: redpanda
  ports:
    - port: 9092
      targetPort: 9092 