apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
  namespace: {{ .Values.global.namespace | default "data-platform-dev" }}
spec:
  serviceName: redpanda
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
        - name: redpanda
          image: vectorized/redpanda:v22.2.1
          ports:
            - containerPort: 9092 