# Global configuration
global:
  environment: dev
  namespace: td-pipeline
  
  # Image configuration
  images:
    registry: ""
    pullPolicy: IfNotPresent
    
  # AWS Configuration
  aws:
    region: us-east-1
    
  # S3 Configuration
  s3:
    bucket: td-pipeline-dev
    
  # Database Configuration
  database:
    host: localhost
    port: 5432
    name: source_db
    
  # Kafka Configuration
  kafka:
    bootstrapServers: "redpanda:9092"
    
  # Resource defaults
  resources:
    small:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 500m
    medium:
      requests:
        memory: 512Mi
        cpu: 500m
      limits:
        memory: 1Gi
        cpu: 1000m
    large:
      requests:
        memory: 1Gi
        cpu: 1000m
      limits:
        memory: 2Gi
        cpu: 2000m

# Component enablement
redpanda:
  enabled: true
  
kafka-connect:
  enabled: true
  
flink:
  enabled: true
  
postgres:
  enabled: false  # External database
