apiVersion: v1
kind: ConfigMap
metadata:
  name: localstack-init-scripts
  labels:
    {{- include "localstack.labels" . | nindent 4 }}
data:
  init-s3.sh: |
    #!/bin/bash
    
    echo "Waiting for LocalStack to be ready..."
    until curl -f http://localhost:4566/_localstack/health; do
      echo "Waiting for LocalStack..."
      sleep 5
    done
    
    echo "Creating S3 bucket for CDC data..."
    awslocal s3 mb s3://cdc-data --region us-east-1
    
    echo "Setting bucket policy for public access..."
    awslocal s3api put-bucket-policy --bucket cdc-data --policy '{
      "Version": "2012-10-17",
      "Statement": [
        {
          "Sid": "PublicReadGetObject",
          "Effect": "Allow",
          "Principal": "*",
          "Action": "s3:GetObject",
          "Resource": "arn:aws:s3:::cdc-data/*"
        }
      ]
    }'
    
    echo "Creating folder structure..."
    awslocal s3api put-object --bucket cdc-data --key checkpoints/
    awslocal s3api put-object --bucket cdc-data --key savepoints/
    awslocal s3api put-object --bucket cdc-data --key postgres-cdc/
    
    echo "Listing buckets:"
    awslocal s3 ls
    
    echo "S3 initialization complete!"
