# Override Redpanda chart values for local development
statefulset:
  replicas: 3

auth:
  sasl:
    enabled: false
  
external:
  enabled: true
  type: NodePort
  domain: "localhost"

listeners:
  kafka:
    port: 9092
    external:
      default:
        advertisedPorts: [31092]
  admin:
    port: 9644
    external:
      default:
        advertisedPorts: [31644]
  http:
    port: 8082
    external:
      default:
        advertisedPorts: [30082]

console:
  enabled: true
  service:
    type: NodePort
    nodePort: 30082

storage:
  persistentVolume:
    enabled: true
    size: 20Gi
    storageClass: "standard"

resources:
  cpu: 
    cores: 1
  memory:
    container:
      max: 2Gi

config:
  cluster:
    auto_create_topics_enabled: true
    default_topic_partitions: 3
    default_topic_replications: 3
  tunable:
    log_segment_size: 536870912
    compacted_log_segment_size: 268435456
