# charts/flink/templates/flink-deployment.yaml
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: {{ .Values.flink.jobName }}
  namespace: {{ .Values.global.namespace }}
spec:
  image: {{ .Values.flink.image }}:{{ .Values.flink.tag }}
  flinkVersion: {{ .Values.flink.version }}
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "{{ .Values.flink.taskManager.slots }}"
    state.backend: rocksdb
    state.checkpoints.dir: "s3://{{ .Values.aws.s3.bucket }}/checkpoints"
    state.savepoints.dir: "s3://{{ .Values.aws.s3.bucket }}/savepoints"
    s3.endpoint: https://s3.{{ .Values.aws.s3.region }}.amazonaws.com
    s3.path.style.access: "false"
    s3.access-key:
      valueFrom:
        secretKeyRef:
          name: aws-credentials
          key: access-key-id
    s3.secret-key:
      valueFrom:
        secretKeyRef:
          name: aws-credentials
          key: secret-access-key
  serviceAccount: {{ .Values.flink.serviceAccount }}
  podTemplate:
    spec:
      containers:
      - name: flink-main-container
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "{{ .Values.kafkaConnect.clusterName }}-kafka-bootstrap:9092"
        - name: ENABLE_BUILT_IN_PLUGINS
          value: "flink-s3-fs-hadoop-{{ .Values.flink.version }}.jar"
  jobManager:
    resource:
      memory: {{ .Values.flink.jobManager.memory }}
      cpu: {{ .Values.flink.jobManager.cpu }}
  taskManager:
    resource:
      memory: {{ .Values.flink.taskManager.memory }}
      cpu: {{ .Values.flink.taskManager.cpu }}
  job:
    jarURI: local:///opt/flink/lib/cdc-processor.jar
    parallelism: {{ .Values.flink.parallelism }}
    upgradeMode: savepoint
