{{- if .Values.sealedSecrets.enabled }}
{{- range $path, $bytes := .Files.Glob (printf "secrets/%s/*" .Values.global.environment) }}
{{- $secret := $.Files.Get $path | fromYaml }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $secret.metadata.name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "td-pipeline.labels" $ | nindent 4 }}
spec:
  encryptedData:
    {{- range $key, $value := $secret.data }}
    {{ $key }}: {{ $value }}
    {{- end }}
  template:
    metadata:
      name: {{ $secret.metadata.name }}
      namespace: {{ $.Values.global.namespace }}
    type: {{ $secret.type | default "Opaque" }}
{{- end }}
{{- end }}
